### PR TITLE
Fix broken IAB Zoom on PDF source

### PR DESCRIPTION
**Pull request by giancarlobi**
@DiegoPino I found this was broken after last PR, this patch fix it, please check if ok also for you. I added a your function at the end because not available in this js file, I think could be optimized.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@giancarlobi great! Can you explain what was wrong? I also saw it broken but was not clear on the issue. Also, what happens if the manifest is not using FULL (just a doubt because I do not understand it yet but I totally trust you on this). What about the other pull and the padding? Thanks for fixing this friend!!

**Comment by giancarlobi** [comment]
Dear friend, I'm just writing code (a draft) for pdf searchable and how to check and select between tesseract and djvu2hocr, I hope (if my neurons kept alive) to end in this night.
With ZOOM I found that after last PR, when source are PDFs, the value returned here getPageProp(indices[0], 'infojson') is NULL while if source is TIFF that doesn't happen. So I revert to old style by getPageURI + query params due to pdf page query.
About if manifest doesn't use FULL we have to check, I feel it has to work anyway, to check
About padding, I saw that if increase of 1 (yes, one) px the container then the last page can go up how much needed to nav bar to recognize that changed, a silly math rounding issue, I suppose.

**Comment by DiegoPino** [comment]
Perfect. Makes sense. I will merge during my afternoon and will check with other manifests later tonight! Thanks!!!

**Comment by giancarlobi** [comment]
> Perfect. Makes sense. I will merge during my afternoon and will check with other manifests later tonight! Thanks!!!

It's Sunday, friend, so no rush and merge and check when you have free time, please.

**Comment by DiegoPino** [comment]
Sunday who? hahaha

**Pull request merged**
