### PR TITLE
ISSUE-106b:API builder/controller re-roll for 1.4.0

### PR DESCRIPTION
**Pull request by DiegoPino**
See #106 but this time robust, well done (sorry,  I was a mess in 2021) and fully functional

This can't be merged without me finishing the latest quirks (Cache clearing + invalidation + reusing existing metadata controller like IIIF Content Search API does) + better config form validation. Also we need to provide by default the configs + views + templates so this can be used out of the box by users.

Will keep adding things this week (Dec 18-24 2023)

### CODE REVIEW

**Comment by alliomeria** [comment]
Thank you for baking this into Archipelago, @DiegoPino! 🌟 Local testing going great so far, and will stay tuned for the refinements we discussed earlier today.

**Comment by DiegoPino** [comment]
quizás, quizás we can close that ticket soon! Getting 4 years old anytime :) Thanks for testing and for the encouragement

**Comment by DiegoPino** [comment]
@alliomeria do we need to provide an example/premade OAI stream for 1.4.0 (when release time comes)? How do we document this? Is April still Archipelago month for this/later? Are dandelions  yellow? I don't know, I have seen white and pink ones. I feel it is ready for a beta test (merge)

**Comment by alliomeria** [comment]
Sounds like a great plan to include an example/premade OAI stream for 1.4.0 @DiegoPino

I think we can definitely reuse the local test templates we've been working with, and settings, can swap in the Archipelago Default DC + mods templates in place of the ones we customized for our partner too. 

Also happy to help document and all that good multicolored springtime jazz 🌼 🌸 💮

**Pull request merged**
