### PR TITLE
ISSUE-149: Added 'fail_to_id' argument to \Drupal\format_strawberryfield\TwigExtension::entityIdsByLabel

### PR DESCRIPTION
**Pull request by patdunlavey**
See https://github.com/esmero/format_strawberryfield/issues/149

# What:
See ISSUE-149 for rationale.

This adds an argument to \Drupal\format_strawberryfield\TwigExtension::entityIdsByLabel, `$fail_to_id`, to tell the function that if
- $fail_to_id is true (default)
- the $label value fails to match an existing entity
- the $label value is numeric
...then check to see if the value is an entity id. If so, then just return the value.

The biggest code changes are around exception handling, since we now have two places that could trigger an exception. So I moved the exception handler to a separate method.

@DiegoPino, I decided to use  `\Drupal::entityTypeManager()->getStorage($entity_type)->load($label)` rather than another EntityQuery, mainly because I'm lazy and don't want to have to hard code entity id field names. I suspect there's a better way to do that which doesn't involve actually loading the entity, though I didn't see an obvious one looking at EntityStorageBase.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@patdunlavey this may be just me but maybe you do not need this (you may say yes and we go ahead, no worries)
Let me explain: 
- In a label based operation you are Getting the ID for a label. And you are passing already the Entity Type and the Bundle of any, and your extension will return the numeric ID.

So, what if for the case your input is a number (or many numbers)

You try in the twig template https://github.com/esmero/format_strawberryfield/blob/bd84b20798106fc4f5761cedc27dc1a3124b10f3/src/TwigExtension.php#L26-L30
```Twig
{% for ids_or_label in data.my_ids_or_labels %}
  {% if ids_or_label is instanceof("scalar") %} 
  // do the logic you need for numbers. Maybe load them via bamboo? Or you can go for "int" to be strict? Maybe just pass them through?
  {% else %}
 // Call the label resolver 
  {% endif %}
{% endfor %}
````

Just a silly idea.

**Comment by patdunlavey** [comment]
Thanks @DiegoPino . I know it's an edge case, but entity labels can be numers. So I think we need to actually look to see if there is an entity with that label, even if the label is a number. Only if that fails, then look to see if it's an entity id. A further consideration: if we assume that numeric entity labels are entity ids, and don't actually check if it's a valid entity id, then we could pass through an invalid entity id.

**Comment by DiegoPino** [comment]
@patdunlavey let me think about this. Because if your Labels can be a number, then how do you know what was intended by the user? There can be a label "22" and also a term "22"... Maybe, for the sake of consistency you could use entity paths for non labels entity:taxonomy:2 ? 

The issue about invalid entity id's could need a different extension. One that uses a list of Ids in an entity query and returns only back the ones that match.  I kinda feel it is better to have (for your edge cases) separate functions instead of functions with too many arguments and logic. Let's talk about this in Slack tomorrow morning and figure out the Pros and Cons of this, happy to get this reviewed and merged but I want to be sure it covers at least the "22" label v/s "22" id thing

**Comment by DiegoPino** [comment]
@patdunlavey do you have any comments on this? Just wonder if you want this into RC2 and if my reply added just confusion. Let me know! Happy we can work this out

**Comment by DiegoPino** [comment]
@patdunlavey this is stale. Do you mind closing it? Or maybe you went another route? Thanks!

**Comment by patdunlavey** [comment]
Yes. Stale. Closing. Thanks!!

**Pull request closed without merging**
