### PR TITLE
Issue-447: missing accessCheck in TwigExtension::entityIdsByLabel

### PR DESCRIPTION
**Pull request by patdunlavey**
- Added entity query access check in TwigExtension::entityIdsByLabel

### CODE REVIEW

**Comment by DiegoPino** [comment]
@patdunlavey since this is user exposed, probably ->accessCheck(TRUE) ?

**Review by DiegoPino — APPROVED** [review]

**Comment by patdunlavey** [comment]
After discussion on the [issue](https://github.com/esmero/format_strawberryfield/issues/447), I agreed to set the accessCheck to TRUE. I also think we can leave 1.3.x as-is .

**Comment by DiegoPino** [comment]
@patdunlavey if you have troubles with AMI imports (please check with background processing bc the user might be different) let me know and I make a quick power/move edit back to FALSE.

**Comment by patdunlavey** [comment]
Thank you sir!

**Pull request merged**
